#!/bin/bash
background        false
out_to_x          false
own_window        false
out_to_console    yes
update_interval   1
total_run_times   0
short_units       yes
uppercase         false
use_spacer        no
max_text_width    0
short_units       true
if_up_strictness = "address"
override_utf8_locale = false
# Use Xft?
use_xft yes

# Xft font when Xft is enabled
xftfont snap:Bold:size=10

TEXT
[

# 🔋
  # }
  #   { "full_text" : "${exec setxkbmap -v 7 | grep layout | awk '{print $2}'}",
  #     "color": "\#586E75",
  #     "separator": false,
  #     "separator_block_width": 3
  # },

  {
      "full_text": "   ${time  %a %d/%m }",
      "color": "\#586E75",
      "separator": false,
      "separator_block_width": 3
  },

  {
      "full_text": " ${time  %H:%M:%S }",
      "color": "\#FDF6E3",
      "background": "\#6C71C4",
      "separator": false,
      "separator_block_width": 3
  }

],
